export const TARGET_FIELDS = [
  "Reference",
  "Address",
  "City",
  "State",
  "Zip",
  "County",
  "Country",
  "Building Value",
  "Contents",
  "BI",
  "Occupancy",
  "Construction",
  "Storeys",
  "Number of Buildings",
  "Year Built",
  "Fire Sprinklers (Y/N)",
  "Other",
];
